### ISSUE TITLE
Code of MeliusNet

### ISSUE THREAD

**Issue by ychzhang** [hpi-xnor/BMXNet-v2#12]
Hi, I recently read your paper MeliusNet, but I couldn't find the code in this repo. Could you please explicitly point out the model and training file? Thanks!

**Comment by Jopyth** [comment]
You can find the [training script](https://github.com/hpi-xnor/BMXNet-v2-examples/blob/master/image_classification.py) and [model code](https://github.com/hpi-xnor/BMXNet-v2-examples/blob/master/binary_models/meliusnet.py) in the example repository.
