### ISSUE TITLE
Build instructions macOS: error with -std=c++11 flag

### ISSUE THREAD

**Issue by simonmaurer** [hpi-xnor/BMXNet-v2#7]
## Description
When trying to build BMXNet v2 using Ninja for macOS environment the process fails when compiling C file

## Environment info (Required)
macOS 10.13.6
CMake 3.12.3
Ninja 1.9.0

## Build info (Required if built from source)

Compiler (gcc/clang/mingw/visual studio):
- Apple LLVM version 10.0.0 (clang-1000.11.45.5) - w/o OpenMP
- llvm: stable 8.0.0 (w. OpenMP) via brew

MXNet commit hash:
d0aaf813be3a090cb5ff41b9451f1c14a4e5036a

Build config:
`
cmake .. -G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DUSE_CUDA=FALSE \
-DUSE_OPENCV=FALSE \
-DUSE_OPENMP=FALSE \
-DUSE_GPERFTOOLS=OFF
`

## Error Message:
[240/270] Building C object CMakeFiles/mxnet.dir/dummy.c.o
FAILED: CMakeFiles/mxnet.dir/dummy.c.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DBINARY_WORD_32=1 -DBINARY_WORD_64=0 -DDMLC_USE_CXX11 -DDMLC_USE_CXX11=1 -DMSHADOW_IN_CXX11 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_SSE=1 -DMXNET_USE_LAPACK=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_OPENCV=0 -DNDEBUG=1 -Dmxnet_EXPORTS -I../include -I../src -I../3rdparty/mshadow -I../3rdparty/cub -I../3rdparty/tvm/nnvm/include -I../3rdparty/tvm/include -I../3rdparty/dmlc-core/include -I../3rdparty/dlpack/include -isystem /System/Library/Frameworks/vecLib.framework/Headers -Wno-braced-scalar-init -O3 -msse2 -std=c++11 -mf16c -march=native -mpopcnt -funroll-loops -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/mxnet.dir/dummy.c.o -MF CMakeFiles/mxnet.dir/dummy.c.o.d -o CMakeFiles/mxnet.dir/dummy.c.o   -c dummy.c
error: invalid argument '-std=c++11' not allowed with 'C'
[246/270] Building CXX object CMakeFil...or/tensor/elemwise_unary_op_basic.cc.o

## Steps to reproduce
1. exactly as described [here](https://github.com/hpi-xnor/BMXNet-v2-wiki/blob/master/building.md)

## What have you tried to solve it?

1. set build instructions with OpenMP on
2. added flag -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -std=c++11"
3. using make instead of Ninja (see error below, the compile process still continues as opposed to the error aboce with Ninja)

## Error message with make:
[  6%] Linking CXX shared library libconverter.dylib
Undefined symbols for architecture x86_64:
  "dmlc::Stream::Create(char const*, char const*, bool)", referenced from:
      convert_params_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.cpp.o
  "mxnet::Engine::Get()", referenced from:
      mxnet::NDArray::Chunk::Chunk(nnvm::TShape, mxnet::Context, bool, int) in main.cpp.o
  "mxnet::NDArray::Load(dmlc::Stream*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> >*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >*)", referenced from:
      convert_params_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.cpp.o
  "mxnet::NDArray::Save(dmlc::Stream*, std::__1::vector<mxnet::NDArray, std::__1::allocator<mxnet::NDArray> > const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&)", referenced from:
      convert_params_file(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in main.cpp.o
  "mxnet::NDArray::Chunk::~Chunk()", referenced from:
      std::__1::__shared_ptr_emplace<mxnet::NDArray::Chunk, std::__1::allocator<mxnet::NDArray::Chunk> >::~__shared_ptr_emplace() in main.cpp.o
      std::__1::__shared_ptr_emplace<mxnet::NDArray::Chunk, std::__1::allocator<mxnet::NDArray::Chunk> >::~__shared_ptr_emplace() in main.cpp.o
      std::__1::__shared_ptr_emplace<mxnet::NDArray::Chunk, std::__1::allocator<mxnet::NDArray::Chunk> >::__on_zero_shared() in main.cpp.o
  "mxnet::Storage::Get()", referenced from:
      mxnet::NDArray::Chunk::Chunk(nnvm::TShape, mxnet::Context, bool, int) in main.cpp.o
      mxnet::NDArray::CheckAndAlloc() const in main.cpp.o
  "mxnet::NDArray::SetTBlob() const", referenced from:
      convert_to_binary_row(mxnet::NDArray&) in main.cpp.o
      transpose(mxnet::NDArray&) in main.cpp.o
      transpose_and_convert_to_binary_col(mxnet::NDArray&) in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [tools/binary_converter/libconverter.dylib] Error 1
make[1]: *** [tools/binary_converter/CMakeFiles/converter.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
...continues...
[ 83%] Linking CXX static library libmxnet.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(rtc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(onnx_to_tensorrt.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(tensorrt_pass.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(trt_graph_executor.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(nnvm_to_onnx.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(tensorrt.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(cudnn_algoreg.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(cudnn_batch_norm.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_act.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_base.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_concat.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_convolution.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_copy.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_deconvolution.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_fully_connected.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_pooling.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_softmax.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_sum.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(nnpack_util.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_quantized_concat.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_quantized_conv.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_quantized_pooling.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_conv.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_conv_post_quantize_property.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_conv_property.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(vtune.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(rtc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(onnx_to_tensorrt.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(tensorrt_pass.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(trt_graph_executor.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(nnvm_to_onnx.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(tensorrt.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(cudnn_algoreg.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(cudnn_batch_norm.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_act.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_base.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_concat.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_convolution.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_copy.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_deconvolution.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_fully_connected.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_pooling.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_softmax.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_sum.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(nnpack_util.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_quantized_concat.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_quantized_conv.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_quantized_pooling.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_conv.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_conv_post_quantize_property.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(mkldnn_conv_property.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libmxnet.a(vtune.cc.o) has no symbols
[ 83%] Built target mxnet_static
make: *** [all] Error 2

**Comment by Jopyth** [comment]
This seems to be a specific problem for clang, but unfortunately we do not have anyone developing on MacOS so it could be hard to fix this.

The `-std=c++11` option for `dummy.c` is set in my buildfiles as well, however gcc/g++ does not seem to mind it.

Here is two quick ideas for a possible solution:

- Try finding a line in your ninja file (`build/build.ninja`) that starts like this:
```build CMakeFiles/mxnet.dir/dummy.c.o: [...]```
3 lines below should be the offending flag:
```FLAGS = -Wall -Wno-unknown-pragmas -Wno-sign-compare -O3 -msse2 -std=c++11 [...]```
Simply deleting the `-std=c++11` could solve the problem (until you run cmake again and the manually modified file is overwritten.

- If you do not need the model-converter on this particular machine you could build with `make` and "disable" the build of our model converter (delete tools/binary_converter).

**Comment by simonmaurer** [comment]
@Jopyth will try you recommendations, thanks.
are the config.mk, respectively the osx.mk not involved in the build process anymore, ie. if I follow the guidelines of the original MXNet ?

**Comment by simonmaurer** [comment]
@Jopyth in the meantime I tried two different approaches:
1) used _make_ instead of _Ninja_, in that case the above error does not appear but it fails to compile due to OpenCV references (although **USE_OPENCV=FALSE**):
`[25/274] Building CXX object CMakeFile...atic.dir/src/io/image_aug_default.cc.o
FAILED: CMakeFiles/mxnet_static.dir/src/io/image_aug_default.cc.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBINARY_WORD_32=1 -DBINARY_WORD_64=0 -DDMLC_USE_CXX11 -DDMLC_USE_CXX11=1 -DMSHADOW_IN_CXX11 -DMSHADOW_USE_CBLAS=1 -DMSHADOW_USE_CUDA=0 -DMSHADOW_USE_MKL=0 -DMSHADOW_USE_SSE=1 -DMXNET_USE_LAPACK=1 -DMXNET_USE_NCCL=0 -DMXNET_USE_OPENCV=1 -DNDEBUG=1 -I../include -I../src -I../3rdparty/mshadow -I../3rdparty/cub -I../3rdparty/tvm/nnvm/include -I../3rdparty/tvm/include -I../3rdparty/dmlc-core/include -I../3rdparty/dlpack/include -isystem /System/Library/Frameworks/vecLib.framework/Headers -isystem /usr/local/include/opencv4 -Wno-braced-scalar-init -O3 -msse2 -std=c++11 -mf16c -march=native -mpopcnt -funroll-loops -std=c++0x -O3 -DNDEBUG -fPIC -MD -MT CMakeFiles/mxnet_static.dir/src/io/image_aug_default.cc.o -MF CMakeFiles/mxnet_static.dir/src/io/image_aug_default.cc.o.d -o CMakeFiles/mxnet_static.dir/src/io/image_aug_default.cc.o -c ../src/io/image_aug_default.cc
../src/io/image_aug_default.cc:482:32: error: use of undeclared identifier 'CV_RGB2GRAY'
          cvtColor(res, temp_, CV_RGB2GRAY);
                               ^
../src/io/image_aug_default.cc:488:32: error: use of undeclared identifier 'CV_RGB2GRAY'
          cvtColor(res, temp_, CV_RGB2GRAY);
                               ^
../src/io/image_aug_default.cc:489:34: error: use of undeclared identifier 'CV_GRAY2BGR'
          cvtColor(temp_, temp_, CV_GRAY2BGR);
                                 ^
../src/io/image_aug_default.cc:498:26: error: use of undeclared identifier 'CV_BGR2HLS'
      cvtColor(res, res, CV_BGR2HLS);
                         ^
../src/io/image_aug_default.cc:518:26: error: use of undeclared identifier 'CV_HLS2BGR'
      cvtColor(res, res, CV_HLS2BGR);
                         ^
5 errors generated.`

2) changed the CMakeLists.txt:
`set(DUMMY_SOURCE ${CMAKE_BINARY_DIR}/dummy.c)`
to
`set(DUMMY_SOURCE ${CMAKE_BINARY_DIR}/dummy.cc)`
In that case the ''-std=c++11" error disappears as well, but with the same OpenCV reference errors.

**Comment by simonmaurer** [comment]
> The `-std=c++11` option for `dummy.c` is set in my buildfiles as well, however gcc/g++ does throw an error (only a warning).
> 
> Here is two quick ideas for a possible solution:
> 
> * Try finding a line in your ninja file (`build/build.ninja`) that starts like this:
>   `build CMakeFiles/mxnet.dir/dummy.c.o: [...]`
>   3 lines below should be the offending flag:
>   `FLAGS = -Wall -Wno-unknown-pragmas -Wno-sign-compare -O3 -msse2 -std=c++11 [...]`
>   Simply deleting the `-std=c++11` should solve the problem (until you run cmake again and the manually modified file is overwritten.
> * If you do not need the model-converter on this particular machine you could build with `make` and "disable" the build of our model converter (delete tools/binary_converter).

indeed that worked, so I can conclude that the problem only exists with the _Ninja_ build system whereas _make_

**Comment by simonmaurer** [comment]
> > The `-std=c++11` option for `dummy.c` is set in my buildfiles as well, however gcc/g++ does throw an error (only a warning).
> > Here is two quick ideas for a possible solution:
> > 
> > * Try finding a line in your ninja file (`build/build.ninja`) that starts like this:
> >   `build CMakeFiles/mxnet.dir/dummy.c.o: [...]`
> >   3 lines below should be the offending flag:
> >   `FLAGS = -Wall -Wno-unknown-pragmas -Wno-sign-compare -O3 -msse2 -std=c++11 [...]`
> >   Simply deleting the `-std=c++11` should solve the problem (until you run cmake again and the manually modified file is overwritten.
> > * If you do not need the model-converter on this particular machine you could build with `make` and "disable" the build of our model converter (delete tools/binary_converter).
> 
> indeed that worked, so I can conclude that the problem only exists with the _Ninja_ build system whereas _make_ works.
> so OpenCV is problematic, it could be reasonable to set `-DMXNET_USE_OPENCV=0` in addition to `-DUSE_OPENCV=0` but only if one wouldnt need OpenCV.

@Jopyth just recompiled MXNet src branch 1.5.0 with -DUSE_OPENCV=1, no undeclared identifiers `CV_RGB2GRAY`

**Comment by simonmaurer** [comment]
solved given @jopyth 's recommendations or adapting CMakeLists.txt
